set number
syntax on
set background=dark
set confirm
set autoindent
set cindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
set backup
set hlsearch
set incsearch
set backspace=2
set mouse=nv
set cursorline 
set ruler
set nocompatible
set clipboard+=unnamed
autocmd BufNewFile *.pl 0r /home/env/.vim/template/template.pl
