library(qtl)
data(hyper)
hyper <- drop.nullmarkers(hyper)
hyper <- est.rf(hyper)
newmap <- est.map(hyper, error.prob=0.01)
hyper <- replace.map(hyper, newmap)
hyper <- calc.errorlod(hyper, error.prob=0.01)
hyper <- sim.geno(hyper)
out.cim <- cim(hyper)
out.cim.pm <- cim(hyper,n.perm=1000)
qtls<-summary(out.cim,perms=out.cim.pm,alphas=0.05,pvalues=TRUE,threshold=4)
qtl<-makeqtl(hyper,chr=qtls$chr,pos=qtls$pos)
fitqtl<-fitqtl(hyper,qtl=qtl)

