library(pegas)
library(adegenet)
library(poppr)
info <- VCFloci("/mnt/ilustre/users/tong.wang/Project/MJ20180320018-yaozhangxiu/evo20180814/step01.vcf-filter/pop.recode.vcf")
popdata<-read.table("/mnt/ilustre/users/tong.wang/Project/MJ20180320018-yaozhangxiu/group.list")
colnames(pop.data)=c("sampleID","groupID")
SNP <- is.snp(info)
x <- length(which(SNP))
x <- read.vcf("/mnt/ilustre/users/tong.wang/Project/MJ20180320018-yaozhangxiu/evo20180814/step01.vcf-filter/pop.recode.vcf", from = 1, to = x)
g<-loci2genind(x)
g<-as.genclone(g)
ploidy(g)<-2
strata(g)<-data.frame(popdata)
amovacc<-poppr.amova(g,~groupID)
signif   <- randtest(amova, nrepet = 999)
pdf("Amova.signif.pdf")
plot(signif)
dev.off()
png("Amova.signif.png")
plot(signif)
dev.off()
d<-cbind(signif$names,signif$alter,signif$expvar,signif$pvalue)
colnames(d)<-c("Test","Alter","Obs","Expectation","Variance","Pvalue")
write.table(file="Amova.signif",d)
write.table(cbind(amova$results,amova$componentsofcovariance), file = "AMOVA.csv")
write.table(amova$statphi, file = "AMOVA.phi")
