perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca1.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca1.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca1.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca10.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca10.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca10.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca11.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca11.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca11.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca12.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca12.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca12.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca2.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca2.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca2.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca3.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca3.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca3.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca4.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca4.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca4.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca5.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca5.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca5.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca6.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca6.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca6.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca7.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca7.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca7.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca8.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca8.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca8.cor.marker 
 perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca9.pri.marker -m /home/huangl/bin/bioinformatics/small-test/sca9.pri.map -o /home/huangl/bin/bioinformatics/small-test/sca9.cor.marker 
 