MSTMap /home/huangl/bin/bioinformatics/small-test/sca1.cor.marker /home/huangl/bin/bioinformatics/small-test/sca1.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca1.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca1.out -o /home/huangl/bin/bioinformatics/small-test/sca1.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca10.cor.marker /home/huangl/bin/bioinformatics/small-test/sca10.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca10.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca10.out -o /home/huangl/bin/bioinformatics/small-test/sca10.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca11.cor.marker /home/huangl/bin/bioinformatics/small-test/sca11.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca11.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca11.out -o /home/huangl/bin/bioinformatics/small-test/sca11.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca12.cor.marker /home/huangl/bin/bioinformatics/small-test/sca12.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca12.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca12.out -o /home/huangl/bin/bioinformatics/small-test/sca12.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca2.cor.marker /home/huangl/bin/bioinformatics/small-test/sca2.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca2.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca2.out -o /home/huangl/bin/bioinformatics/small-test/sca2.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca3.cor.marker /home/huangl/bin/bioinformatics/small-test/sca3.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca3.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca3.out -o /home/huangl/bin/bioinformatics/small-test/sca3.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca4.cor.marker /home/huangl/bin/bioinformatics/small-test/sca4.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca4.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca4.out -o /home/huangl/bin/bioinformatics/small-test/sca4.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca5.cor.marker /home/huangl/bin/bioinformatics/small-test/sca5.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca5.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca5.out -o /home/huangl/bin/bioinformatics/small-test/sca5.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca6.cor.marker /home/huangl/bin/bioinformatics/small-test/sca6.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca6.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca6.out -o /home/huangl/bin/bioinformatics/small-test/sca6.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca7.cor.marker /home/huangl/bin/bioinformatics/small-test/sca7.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca7.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca7.out -o /home/huangl/bin/bioinformatics/small-test/sca7.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca8.cor.marker /home/huangl/bin/bioinformatics/small-test/sca8.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca8.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca8.out -o /home/huangl/bin/bioinformatics/small-test/sca8.marker 
 MSTMap /home/huangl/bin/bioinformatics/small-test/sca9.cor.marker /home/huangl/bin/bioinformatics/small-test/sca9.out &&perl /home/huangl/bin/bioinformatics/Pipeline/06.GMAP/bin/bin/smooth-NOCP.pl -i /home/huangl/bin/bioinformatics/small-test/sca9.cor.marker -m /home/huangl/bin/bioinformatics/small-test/sca9.out -o /home/huangl/bin/bioinformatics/small-test/sca9.marker 
 